### ISSUE TITLE
BioASQ download location

### ISSUE THREAD

**Issue by riebling** [liboyue/BOOM#3]
This is no fault of any of us, or BOOM, but: where can one find the download link for `BioASQ-trainingDataset6b.json` on the BioASQ page? As mentioned in the [BioASQ example README](https://github.com/liboyue/BOOM/blob/master/examples/BioASQ/README.md)

The best I could find is a couple links deep into the site (labeled - as "here" with hover text that does not indicate that the link actually takes you to a download, until you click it) - which leads to a download of a zip archive with ALMOST the right name mentioned in the README: `BioASQ-training6b.zip`. 

Then only after you download (still not knowing what it contains) and click to open the archive, will someone be able to discover "Oh! Here is that file `trainingDataset6b.json` that the README was telling me to download!". So by fixing the README, eliminate 2 complete blind leaps of faith for people who have no prior knowledge of BioASQ

**Comment by liboyue** [comment]
Fixed. Thanks a lot!
